In [1]:
import os
import SimpleITK as sitk

In [2]:
from radiomics import featureextractor
extractor = featureextractor.RadiomicsFeatureExtractor()

In [3]:
import pandas as pd
import numpy as np

/home/euphrates/anaconda3/lib/python3.11/site-packages/pandas/core/computation/expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/home/euphrates/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

In [ ]:
kits_path = "nii"

for case in os.listdir(kits_path):

    case_dir = os.path.join(kits_path, case)

    image_path = os.path.join(case_dir, "imaging.nii.gz")
    mask_path = os.path.join(case_dir, "segmentation.nii.gz")

    image = sitk.ReadImage(image_path)
    mask = sitk.ReadImage(mask_path)

    features = extractor.execute(image, mask)

    row = dict(features)
    row["case_id"] = case
    row["dataset"] = "kits"

GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated

In [6]:
df_nii = pd.DataFrame([row])

In [8]:
row

{'diagnostics_Versions_PyRadiomics': 'v3.0.1',
 'diagnostics_Versions_Numpy': '1.26.4',
 'diagnostics_Versions_SimpleITK': '2.5.3',
 'diagnostics_Versions_PyWavelet': '1.5.0',
 'diagnostics_Versions_Python': '3.11.7',
 'diagnostics_Configuration_Settings': {'minimumROIDimensions': 2,
  'minimumROISize': None,
  'normalize': False,
  'normalizeScale': 1,
  'removeOutliers': None,
  'resampledPixelSpacing': None,
  'interpolator': 'sitkBSpline',
  'preCrop': False,
  'padDistance': 5,
  'distances': [1],
  'force2D': False,
  'force2Ddimension': 0,
  'resegmentRange': None,
  'label': 1,
  'additionalInfo': True},
 'diagnostics_Configuration_EnabledImageTypes': {'Original': {}},
 'diagnostics_Image-original_Hash': '2cfa84e2a91d18e085dfde63ffed67f26144fe73',
 'diagnostics_Image-original_Dimensionality': '3D',
 'diagnostics_Image-original_Spacing': (0.5, 0.919921875, 0.919921875),
 'diagnostics_Image-original_Size': (611, 512, 512),
 'diagnostics_Image-original_Mean': -644.9868647611278,
 'diagnostics_Image-original_Minimum': -1024.0,
 'diagnostics_Image-original_Maximum': 1413.0,
 'diagnostics_Mask-original_Hash': '820ed0dd11f897821e40a7ba0d78c2d273b7ee5b',
 'diagnostics_Mask-original_Spacing': (0.5, 0.919921875, 0.919921875),
 'diagnostics_Mask-original_Size': (611, 512, 512),
 'diagnostics_Mask-original_BoundingBox': (90, 275, 139, 264, 100, 227),
 'diagnostics_Mask-original_VoxelNum': 854483,
 'diagnostics_Mask-original_VolumeNum': 5,
 'diagnostics_Mask-original_CenterOfMassIndex': (223.06070571327925,
  329.5529320068392,
  245.14584140351533),
 'diagnostics_Mask-original_CenterOfMass': (225.51502207237445,
  303.16295112347905,
  -111.53035285663962),
 'original_shape_Elongation': 0.32963613949540066,
 'original_shape_Flatness': 0.18994113129603785,
 'original_shape_LeastAxisLength': 55.80237548686982,
 'original_shape_MajorAxisLength': 293.7877388963085,
 'original_shape_Maximum2DDiameterColumn': array(206.04429573),
 'original_shape_Maximum2DDiameterRow': array(203.55025497),
 'original_shape_Maximum2DDiameterSlice': array(111.47939565),
 'original_shape_Maximum3DDiameter': array(216.7847517),
 'original_shape_MeshVolume': array(361707.13106918),
 'original_shape_MinorAxisLength': 96.84305608086191,
 'original_shape_Sphericity': array(0.48150094),
 'original_shape_SurfaceArea': array(50986.87190952),
 'original_shape_SurfaceVolumeRatio': array(0.14096175),
 'original_shape_VoxelVolume': 361555.7922420502,
 'original_firstorder_10Percentile': array(29.),
 'original_firstorder_90Percentile': array(195.),
 'original_firstorder_Energy': array(1.65931204e+10),
 'original_firstorder_Entropy': array(3.31756918),
 'original_firstorder_InterquartileRange': array(107.),
 'original_firstorder_Kurtosis': array(2.72423824),
 'original_firstorder_Maximum': array(432.),
 'original_firstorder_MeanAbsoluteDeviation': array(56.50916453),
 'original_firstorder_Mean': array(122.15636707),
 'original_firstorder_Median': array(141.),
 'original_firstorder_Minimum': array(-149.),
 'original_firstorder_Range': array(581.),
 'original_firstorder_RobustMeanAbsoluteDeviation': array(42.93830235),
 'original_firstorder_RootMeanSquared': array(139.35171511),
 'original_firstorder_Skewness': array(-0.5284584),
 'original_firstorder_TotalEnergy': array(7.02101596e+09),
 'original_firstorder_Uniformity': array(0.12009557),
 'original_firstorder_Variance': array(4496.72248872),
 'original_glcm_Autocorrelation': array(136.98700199),
 'original_glcm_ClusterProminence': array(1513.91400866),
 'original_glcm_ClusterShade': array(-59.04834504),
 'original_glcm_ClusterTendency': array(24.55693059),
 'original_glcm_Contrast': array(3.3124721),
 'original_glcm_Correlation': array(0.76200058),
 'original_glcm_DifferenceAverage': array(1.25704584),
 'original_glcm_DifferenceEntropy': array(2.07788722),
 'original_glcm_DifferenceVariance': array(1.68454424),
 'original_glcm_Id': array(0.57907193),
 'original_glcm_Idm': array(0.53790886),
 'original_glcm_Idmn': array(0.99444651),
 'original_glcm_Idn': array(0.9525937),
 'original_glcm_Imc1': array(-0.20972385),
 'original_glcm_Imc2': array(0.8512692),
 'original_glcm_InverseVariance': array(0.46339713),
 'original_glcm_JointAverage': array(11.47500842),
 'original_glcm_JointEnergy': array(0.02778713),
 'original_glcm_JointEntropy': array(5.88025796),
 'original_glcm_MCC': array(0.79797038),
 'original_glcm_MaximumProbability': array(0.07146023),
 'original_glcm_SumAverage': array(22.95001683),
 'original_glcm_SumEntropy': array(4.14772346),
 'original_glcm_SumSquares': array(6.96735067),
 'original_gldm_DependenceEntropy': array(7.12763272),
 'original_gldm_DependenceNonUniformity': array(57819.21089243),
 'original_gldm_DependenceNonUniformityNormalized': array(0.06766572),
 'original_gldm_DependenceVariance': array(16.86404861),
 'original_gldm_GrayLevelNonUniformity': array(102619.61998425),
 'original_gldm_GrayLevelVariance': array(7.2786601),
 'original_gldm_HighGrayLevelEmphasis': array(137.37987181),
 'original_gldm_LargeDependenceEmphasis': array(84.81973427),
 'original_gldm_LargeDependenceHighGrayLevelEmphasis': array(12143.94496438),
 'original_gldm_LargeDependenceLowGrayLevelEmphasis': array(0.73777834),
 'original_gldm_LowGrayLevelEmphasis': array(0.01002521),
 'original_gldm_SmallDependenceEmphasis': array(0.05858917),
 'original_gldm_SmallDependenceHighGrayLevelEmphasis': array(6.86632965),
 'original_gldm_SmallDependenceLowGrayLevelEmphasis': array(0.00094448),
 'original_glrlm_GrayLevelNonUniformity': array(68787.00968106),
 'original_glrlm_GrayLevelNonUniformityNormalized': array(0.11154554),
 'original_glrlm_GrayLevelVariance': array(7.65519948),
 'original_glrlm_HighGrayLevelRunEmphasis': array(135.56495335),
 'original_glrlm_LongRunEmphasis': array(2.63059818),
 'original_glrlm_LongRunHighGrayLevelEmphasis': array(367.46958476),
 'original_glrlm_LongRunLowGrayLevelEmphasis': array(0.02491089),
 'original_glrlm_LowGrayLevelRunEmphasis': array(0.01045589),
 'original_glrlm_RunEntropy': array(4.55107529),
 'original_glrlm_RunLengthNonUniformity': array(361466.29157248),
 'original_glrlm_RunLengthNonUniformityNormalized': array(0.581299),
 'original_glrlm_RunPercentage': array(0.72140293),
 'original_glrlm_RunVariance': array(0.65784355),
 'original_glrlm_ShortRunEmphasis': array(0.78887379),
 'original_glrlm_ShortRunHighGrayLevelEmphasis': array(105.66190406),
 'original_glrlm_ShortRunLowGrayLevelEmphasis': array(0.00854673),
 'original_glszm_GrayLevelNonUniformity': array(3204.74181958),
 'original_glszm_GrayLevelNonUniformityNormalized': array(0.08224668),
 'original_glszm_GrayLevelVariance': array(13.96345055),
 'original_glszm_HighGrayLevelZoneEmphasis': array(109.76969075),
 'original_glszm_LargeAreaEmphasis': array(877897.47324522),
 'original_glszm_LargeAreaHighGrayLevelEmphasis': array(1.44345734e+08),
 'original_glszm_LargeAreaLowGrayLevelEmphasis': array(5818.93100905),
 'original_glszm_LowGrayLevelZoneEmphasis': array(0.01966721),
 'original_glszm_SizeZoneNonUniformity': array(11796.10704478),
 'original_glszm_SizeZoneNonUniformityNormalized': array(0.30273597),
 'original_glszm_SmallAreaEmphasis': array(0.56601966),
 'original_glszm_SmallAreaHighGrayLevelEmphasis': array(58.98856303),
 'original_glszm_SmallAreaLowGrayLevelEmphasis': array(0.01194374),
 'original_glszm_ZoneEntropy': array(6.34309015),
 'original_glszm_ZonePercentage': array(0.04560067),
 'original_glszm_ZoneVariance': array(877416.57023839),
 'original_ngtdm_Busyness': array(176.86919327),
 'original_ngtdm_Coarseness': array(1.44401664e-05),
 'original_ngtdm_Complexity': array(217.76286768),
 'original_ngtdm_Contrast': array(0.02147843),
 'original_ngtdm_Strength': array(0.00388949),
 'case_id': 'case_00000',
 'dataset': 'kits'}

In [7]:
df_nii

,diagnostics_Versions_PyRadiomics,diagnostics_Versions_Numpy,diagnostics_Versions_SimpleITK,diagnostics_Versions_PyWavelet,diagnostics_Versions_Python,diagnostics_Configuration_Settings,diagnostics_Configuration_EnabledImageTypes,diagnostics_Image-original_Hash,diagnostics_Image-original_Dimensionality,diagnostics_Image-original_Spacing,...,original_glszm_ZoneEntropy,original_glszm_ZonePercentage,original_glszm_ZoneVariance,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength,case_id,dataset
0,v3.0.1,1.26.4,2.5.3,1.5.0,3.11.7,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},2cfa84e2a91d18e085dfde63ffed67f26144fe73,3D,"(0.5, 0.919921875, 0.919921875)",...,6.3430901535151705,0.045600673155580626,877416.5702383879,176.8691932706102,1.4440166404882042e-05,217.7628676832365,0.02147843430654103,0.0038894936529327616,case_00000,kits

In [22]:
import h5py
import numpy as np

hdf5_folder = "hdf5"

for file in os.listdir(hdf5_folder):

    if not file.endswith(".hdf5"):
        continue

    path = os.path.join(hdf5_folder, file)

    with h5py.File(path, "r") as f:

        image_array = f["portven"][:]
        mask_array = f["mask"][:]

        image = sitk.GetImageFromArray(image_array)
        mask = sitk.GetImageFromArray(mask_array)

        features = extractor.execute(image, mask)

        row_h= dict(features)
        row_h["case_id"] = file
        row_h["dataset"] = "hdf5"
    with open(output_path,'w') as x:
        w = csv.writer(x)
        w.writerows(row_h.values)

GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated

TypeError: 'builtin_function_or_method' object is not iterable

In [7]:
import h5py
import numpy as np
import csv
ls = []
hdf5_folder = '/media/euphrates/DS-Backup/angiomyolipoma/ucsf-rmac-dataset'
rd_mics_hdf5 = "/media/euphrates/DS-Backup/csv_aml_ucsf_rmac"
for file in os.listdir(hdf5_folder):

    input_path = os.path.join(hdf5_folder, file)

    
    
    with h5py.File(input_path, "r") as f:

        image_array = f["portven"][:]
        mask_array = f["mask"][:]

        image = sitk.GetImageFromArray(image_array)
        mask = sitk.GetImageFromArray(mask_array)

        features = extractor.execute(image, mask)

        row_h= dict(features)
        row_h["case_id"] = file
        ls.append(row_h.values())

    
columns = ls[0]
rows = ls[1:]
df_np = pd.DataFrame(rows,columns = columns)
df_np.to_csv("/media/euphrates/DS-Backup/csv_aml_ucsf_rmac/hdf5.csv")

GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated

KeyError: "Unable to open object (object 'portven' doesn't exist)"

In [ ]:
import h5py
import numpy as np
import csv
ls = []
hdf5_folder = '/media/euphrates/DS-Backup/angiomyolipoma/ucsf-rmac-dataset'
rd_mics_hdf5 = "/media/euphrates/DS-Backup/csv_aml_ucsf_rmac"
for file in os.listdir(hdf5_folder):

    input_path = os.path.join(hdf5_folder, file)

    with h5py.File(input_path, "r") as f:
        if "portven" in f:
            image_array = f["portven"][:]
        elif "arterial" in f:
            image_array = f["arterial"][:]
        elif "delay" in f:
            image_array = f["delay"][:]
        elif "noncon" in f:
            image_array = f["noncon"][:]
        else:
            print("No usable phase in:", file)
            continue

        mask_array = f["mask"][:]
    


        image = sitk.GetImageFromArray(image_array)
        mask = sitk.GetImageFromArray(mask_array)

        features = extractor.execute(image, mask)

        row_h= dict(features)
        row_h["case_id"] = file
        ls.append(row_h.values())

    
columns = ls[0]
rows = ls[1:]
df_np = pd.DataFrame(rows,columns = columns)
df_np.to_csv("/media/euphrates/DS-Backup/csv_aml_ucsf_rmac/hdf5.csv")

GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated

In [6]:
os.getcwd()

'/media/euphrates/DS-Backup'

In [27]:
columns = ls[0]

In [28]:
rows = ls[1:]

In [29]:
df_np = pd.DataFrame(rows,columns = columns)

In [30]:
df_np

,diagnostics_Versions_PyRadiomics,diagnostics_Versions_Numpy,diagnostics_Versions_SimpleITK,diagnostics_Versions_PyWavelet,diagnostics_Versions_Python,diagnostics_Configuration_Settings,diagnostics_Configuration_EnabledImageTypes,diagnostics_Image-original_Hash,diagnostics_Image-original_Dimensionality,diagnostics_Image-original_Spacing,...,original_glszm_SmallAreaLowGrayLevelEmphasis,original_glszm_ZoneEntropy,original_glszm_ZonePercentage,original_glszm_ZoneVariance,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength,case_id
0,v3.0.1,1.26.4,2.5.3,1.5.0,3.11.7,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},cac20675bbd341dc19ec45eb69daecb15fb057dd,3D,"(1.0, 1.0, 1.0)",...,0.06123971977104075,4.826604550223263,0.04427645788336933,9447.413444378346,3.306996986659604,0.004428332975428683,26.158908325245086,0.02307656613152183,0.16982067525940164,1a7jTnjpn9.hdf5
1,v3.0.1,1.26.4,2.5.3,1.5.0,3.11.7,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},42bf21de5964f3604abd8f35020f6fa7a46bedd1,3D,"(1.0, 1.0, 1.0)",...,0.008817743109460915,6.160008515242383,0.04804994388327722,33723.82000959028,5.948833963922284,0.0008109470185161448,84.15583495069353,0.027599953467513944,0.09845892501898494,nSIvfJZBlK.hdf5

In [7]:
ls[0]

dict_keys(['diagnostics_Versions_PyRadiomics', 'diagnostics_Versions_Numpy', 'diagnostics_Versions_SimpleITK', 'diagnostics_Versions_PyWavelet', 'diagnostics_Versions_Python', 'diagnostics_Configuration_Settings', 'diagnostics_Configuration_EnabledImageTypes', 'diagnostics_Image-original_Hash', 'diagnostics_Image-original_Dimensionality', 'diagnostics_Image-original_Spacing', 'diagnostics_Image-original_Size', 'diagnostics_Image-original_Mean', 'diagnostics_Image-original_Minimum', 'diagnostics_Image-original_Maximum', 'diagnostics_Mask-original_Hash', 'diagnostics_Mask-original_Spacing', 'diagnostics_Mask-original_Size', 'diagnostics_Mask-original_BoundingBox', 'diagnostics_Mask-original_VoxelNum', 'diagnostics_Mask-original_VolumeNum', 'diagnostics_Mask-original_CenterOfMassIndex', 'diagnostics_Mask-original_CenterOfMass', 'original_shape_Elongation', 'original_shape_Flatness', 'original_shape_LeastAxisLength', 'original_shape_MajorAxisLength', 'original_shape_Maximum2DDiameterColumn', 'original_shape_Maximum2DDiameterRow', 'original_shape_Maximum2DDiameterSlice', 'original_shape_Maximum3DDiameter', 'original_shape_MeshVolume', 'original_shape_MinorAxisLength', 'original_shape_Sphericity', 'original_shape_SurfaceArea', 'original_shape_SurfaceVolumeRatio', 'original_shape_VoxelVolume', 'original_firstorder_10Percentile', 'original_firstorder_90Percentile', 'original_firstorder_Energy', 'original_firstorder_Entropy', 'original_firstorder_InterquartileRange', 'original_firstorder_Kurtosis', 'original_firstorder_Maximum', 'original_firstorder_MeanAbsoluteDeviation', 'original_firstorder_Mean', 'original_firstorder_Median', 'original_firstorder_Minimum', 'original_firstorder_Range', 'original_firstorder_RobustMeanAbsoluteDeviation', 'original_firstorder_RootMeanSquared', 'original_firstorder_Skewness', 'original_firstorder_TotalEnergy', 'original_firstorder_Uniformity', 'original_firstorder_Variance', 'original_glcm_Autocorrelation', 'original_glcm_ClusterProminence', 'original_glcm_ClusterShade', 'original_glcm_ClusterTendency', 'original_glcm_Contrast', 'original_glcm_Correlation', 'original_glcm_DifferenceAverage', 'original_glcm_DifferenceEntropy', 'original_glcm_DifferenceVariance', 'original_glcm_Id', 'original_glcm_Idm', 'original_glcm_Idmn', 'original_glcm_Idn', 'original_glcm_Imc1', 'original_glcm_Imc2', 'original_glcm_InverseVariance', 'original_glcm_JointAverage', 'original_glcm_JointEnergy', 'original_glcm_JointEntropy', 'original_glcm_MCC', 'original_glcm_MaximumProbability', 'original_glcm_SumAverage', 'original_glcm_SumEntropy', 'original_glcm_SumSquares', 'original_gldm_DependenceEntropy', 'original_gldm_DependenceNonUniformity', 'original_gldm_DependenceNonUniformityNormalized', 'original_gldm_DependenceVariance', 'original_gldm_GrayLevelNonUniformity', 'original_gldm_GrayLevelVariance', 'original_gldm_HighGrayLevelEmphasis', 'original_gldm_LargeDependenceEmphasis', 'original_gldm_LargeDependenceHighGrayLevelEmphasis', 'original_gldm_LargeDependenceLowGrayLevelEmphasis', 'original_gldm_LowGrayLevelEmphasis', 'original_gldm_SmallDependenceEmphasis', 'original_gldm_SmallDependenceHighGrayLevelEmphasis', 'original_gldm_SmallDependenceLowGrayLevelEmphasis', 'original_glrlm_GrayLevelNonUniformity', 'original_glrlm_GrayLevelNonUniformityNormalized', 'original_glrlm_GrayLevelVariance', 'original_glrlm_HighGrayLevelRunEmphasis', 'original_glrlm_LongRunEmphasis', 'original_glrlm_LongRunHighGrayLevelEmphasis', 'original_glrlm_LongRunLowGrayLevelEmphasis', 'original_glrlm_LowGrayLevelRunEmphasis', 'original_glrlm_RunEntropy', 'original_glrlm_RunLengthNonUniformity', 'original_glrlm_RunLengthNonUniformityNormalized', 'original_glrlm_RunPercentage', 'original_glrlm_RunVariance', 'original_glrlm_ShortRunEmphasis', 'original_glrlm_ShortRunHighGrayLevelEmphasis', 'original_glrlm_ShortRunLowGrayLevelEmphasis', 'original_glszm_GrayLevelNonUniformity', 'original_glszm_GrayLevelNonUniformityNormalized', 'original_glszm_GrayLevelVariance', 'original_glszm_HighGrayLevelZoneEmphasis', 'original_glszm_LargeAreaEmphasis', 'original_glszm_LargeAreaHighGrayLevelEmphasis', 'original_glszm_LargeAreaLowGrayLevelEmphasis', 'original_glszm_LowGrayLevelZoneEmphasis', 'original_glszm_SizeZoneNonUniformity', 'original_glszm_SizeZoneNonUniformityNormalized', 'original_glszm_SmallAreaEmphasis', 'original_glszm_SmallAreaHighGrayLevelEmphasis', 'original_glszm_SmallAreaLowGrayLevelEmphasis', 'original_glszm_ZoneEntropy', 'original_glszm_ZonePercentage', 'original_glszm_ZoneVariance', 'original_ngtdm_Busyness', 'original_ngtdm_Coarseness', 'original_ngtdm_Complexity', 'original_ngtdm_Contrast', 'original_ngtdm_Strength', 'case_id'])

In [17]:
row_h.values()

dict_values(['v3.0.1', '1.26.4', '2.5.3', '1.5.0', '3.11.7', {'minimumROIDimensions': 2, 'minimumROISize': None, 'normalize': False, 'normalizeScale': 1, 'removeOutliers': None, 'resampledPixelSpacing': None, 'interpolator': 'sitkBSpline', 'preCrop': False, 'padDistance': 5, 'distances': [1], 'force2D': False, 'force2Ddimension': 0, 'resegmentRange': None, 'label': 1, 'additionalInfo': True}, {'Original': {}}, 'cac20675bbd341dc19ec45eb69daecb15fb057dd', '3D', (1.0, 1.0, 1.0), (30, 512, 512), -1039.834688266788, -3024.0, 1285.068359375, 'dc421630be749d16fe355845f33ea6d6d0e441c4', (1.0, 1.0, 1.0), (30, 512, 512), (13, 319, 243, 4, 28, 24), 1852, 1, (14.330453563714903, 332.33585313174945, 254.951403887689), (14.330453563714903, 332.33585313174945, 254.951403887689), 0.8326458755612453, 0.12909042081288277, 3.764063828160706, 29.15835121195194, array(24.), array(35.4682957), array(28.0713377), array(35.4682957), array(1825.58333333), 24.278580874798017, array(0.48752939), array(1481.66866333), array(0.81161382), 1852.0, array(91.09812393), array(167.96594238), array(30855850.68278018), array(2.3403517), array(32.19499588), array(4.0144617), array(227.55415344), array(23.12992732), array(125.17354009), array(123.23176575), array(1.26012444), array(226.294029), array(14.12695305), array(129.07682403), array(-0.00728251), array(30855850.68278018), array(0.25333595), array(992.4113634), array(31.12463487), array(72.70334279), array(2.63174929), array(4.12901407), array(1.47098231), array(0.45759041), array(0.85922314), array(1.62199038), array(0.68309713), array(0.65508932), array(0.62961381), array(0.98606213), array(0.92625344), array(-0.14247344), array(0.61113907), array(0.47333268), array(5.51905132), array(0.09161687), array(4.11126082), array(0.60487781), array(0.18631406), array(11.03810265), array(2.96946918), array(1.3999991), array(5.99780546), array(126.57235421), array(0.0683436), array(17.26585001), array(469.17818575), array(1.64956337), array(31.92332613), array(90.15982721), array(2848.3174946), array(3.20758675), array(0.04421488), array(0.05314472), array(1.55334527), array(0.00466118), array(296.46808486), array(0.22520253), array(1.90461541), array(31.84840384), array(3.29529965), array(105.54818451), array(0.13195635), array(0.04753603), array(3.61198096), array(774.68294466), array(0.5620964), array(0.71008473), array(0.95156434), array(0.7642796), array(24.24330307), array(0.03873046), array(15.43902439), array(0.18828079), array(4.64083879), array(26.91463415), array(9957.51219512), array(299816.14634146), array(349.71745065), array(0.10705579), array(21.92682927), array(0.26740036), array(0.52875801), array(15.03666609), array(0.06123972), array(4.82660455), array(0.04427646), array(9447.41344438), array(3.30699699), array(0.00442833), array(26.15890833), array(0.02307657), array(0.16982068), '1a7jTnjpn9.hdf5'])

In [15]:
pd.read_csv("hdf5_csv/1a7jTnjpn9.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'hdf5_csv/1a7jTnjpn9.csv'

In [10]:
df_h = pd.DataFrame([row_h])

In [11]:
row_h

{'diagnostics_Versions_PyRadiomics': 'v3.0.1',
 'diagnostics_Versions_Numpy': '1.26.4',
 'diagnostics_Versions_SimpleITK': '2.5.3',
 'diagnostics_Versions_PyWavelet': '1.5.0',
 'diagnostics_Versions_Python': '3.11.7',
 'diagnostics_Configuration_Settings': {'minimumROIDimensions': 2,
  'minimumROISize': None,
  'normalize': False,
  'normalizeScale': 1,
  'removeOutliers': None,
  'resampledPixelSpacing': None,
  'interpolator': 'sitkBSpline',
  'preCrop': False,
  'padDistance': 5,
  'distances': [1],
  'force2D': False,
  'force2Ddimension': 0,
  'resegmentRange': None,
  'label': 1,
  'additionalInfo': True},
 'diagnostics_Configuration_EnabledImageTypes': {'Original': {}},
 'diagnostics_Image-original_Hash': 'cac20675bbd341dc19ec45eb69daecb15fb057dd',
 'diagnostics_Image-original_Dimensionality': '3D',
 'diagnostics_Image-original_Spacing': (1.0, 1.0, 1.0),
 'diagnostics_Image-original_Size': (30, 512, 512),
 'diagnostics_Image-original_Mean': -1039.834688266788,
 'diagnostics_Image-original_Minimum': -3024.0,
 'diagnostics_Image-original_Maximum': 1285.068359375,
 'diagnostics_Mask-original_Hash': 'dc421630be749d16fe355845f33ea6d6d0e441c4',
 'diagnostics_Mask-original_Spacing': (1.0, 1.0, 1.0),
 'diagnostics_Mask-original_Size': (30, 512, 512),
 'diagnostics_Mask-original_BoundingBox': (13, 319, 243, 4, 28, 24),
 'diagnostics_Mask-original_VoxelNum': 1852,
 'diagnostics_Mask-original_VolumeNum': 1,
 'diagnostics_Mask-original_CenterOfMassIndex': (14.330453563714903,
  332.33585313174945,
  254.951403887689),
 'diagnostics_Mask-original_CenterOfMass': (14.330453563714903,
  332.33585313174945,
  254.951403887689),
 'original_shape_Elongation': 0.8326458755612453,
 'original_shape_Flatness': 0.12909042081288277,
 'original_shape_LeastAxisLength': 3.764063828160706,
 'original_shape_MajorAxisLength': 29.15835121195194,
 'original_shape_Maximum2DDiameterColumn': array(24.),
 'original_shape_Maximum2DDiameterRow': array(35.4682957),
 'original_shape_Maximum2DDiameterSlice': array(28.0713377),
 'original_shape_Maximum3DDiameter': array(35.4682957),
 'original_shape_MeshVolume': array(1825.58333333),
 'original_shape_MinorAxisLength': 24.278580874798017,
 'original_shape_Sphericity': array(0.48752939),
 'original_shape_SurfaceArea': array(1481.66866333),
 'original_shape_SurfaceVolumeRatio': array(0.81161382),
 'original_shape_VoxelVolume': 1852.0,
 'original_firstorder_10Percentile': array(91.09812393),
 'original_firstorder_90Percentile': array(167.96594238),
 'original_firstorder_Energy': array(30855850.68278018),
 'original_firstorder_Entropy': array(2.3403517),
 'original_firstorder_InterquartileRange': array(32.19499588),
 'original_firstorder_Kurtosis': array(4.0144617),
 'original_firstorder_Maximum': array(227.55415344),
 'original_firstorder_MeanAbsoluteDeviation': array(23.12992732),
 'original_firstorder_Mean': array(125.17354009),
 'original_firstorder_Median': array(123.23176575),
 'original_firstorder_Minimum': array(1.26012444),
 'original_firstorder_Range': array(226.294029),
 'original_firstorder_RobustMeanAbsoluteDeviation': array(14.12695305),
 'original_firstorder_RootMeanSquared': array(129.07682403),
 'original_firstorder_Skewness': array(-0.00728251),
 'original_firstorder_TotalEnergy': array(30855850.68278018),
 'original_firstorder_Uniformity': array(0.25333595),
 'original_firstorder_Variance': array(992.4113634),
 'original_glcm_Autocorrelation': array(31.12463487),
 'original_glcm_ClusterProminence': array(72.70334279),
 'original_glcm_ClusterShade': array(2.63174929),
 'original_glcm_ClusterTendency': array(4.12901407),
 'original_glcm_Contrast': array(1.47098231),
 'original_glcm_Correlation': array(0.45759041),
 'original_glcm_DifferenceAverage': array(0.85922314),
 'original_glcm_DifferenceEntropy': array(1.62199038),
 'original_glcm_DifferenceVariance': array(0.68309713),
 'original_glcm_Id': array(0.65508932),
 'original_glcm_Idm': array(0.62961381),
 'original_glcm_Idmn': array(0.98606213),
 'original_glcm_Idn': array(0.92625344),
 'original_glcm_Imc1': array(-0.14247344),
 'original_glcm_Imc2': array(0.61113907),
 'original_glcm_InverseVariance': array(0.47333268),
 'original_glcm_JointAverage': array(5.51905132),
 'original_glcm_JointEnergy': array(0.09161687),
 'original_glcm_JointEntropy': array(4.11126082),
 'original_glcm_MCC': array(0.60487781),
 'original_glcm_MaximumProbability': array(0.18631406),
 'original_glcm_SumAverage': array(11.03810265),
 'original_glcm_SumEntropy': array(2.96946918),
 'original_glcm_SumSquares': array(1.3999991),
 'original_gldm_DependenceEntropy': array(5.99780546),
 'original_gldm_DependenceNonUniformity': array(126.57235421),
 'original_gldm_DependenceNonUniformityNormalized': array(0.0683436),
 'original_gldm_DependenceVariance': array(17.26585001),
 'original_gldm_GrayLevelNonUniformity': array(469.17818575),
 'original_gldm_GrayLevelVariance': array(1.64956337),
 'original_gldm_HighGrayLevelEmphasis': array(31.92332613),
 'original_gldm_LargeDependenceEmphasis': array(90.15982721),
 'original_gldm_LargeDependenceHighGrayLevelEmphasis': array(2848.3174946),
 'original_gldm_LargeDependenceLowGrayLevelEmphasis': array(3.20758675),
 'original_gldm_LowGrayLevelEmphasis': array(0.04421488),
 'original_gldm_SmallDependenceEmphasis': array(0.05314472),
 'original_gldm_SmallDependenceHighGrayLevelEmphasis': array(1.55334527),
 'original_gldm_SmallDependenceLowGrayLevelEmphasis': array(0.00466118),
 'original_glrlm_GrayLevelNonUniformity': array(296.46808486),
 'original_glrlm_GrayLevelNonUniformityNormalized': array(0.22520253),
 'original_glrlm_GrayLevelVariance': array(1.90461541),
 'original_glrlm_HighGrayLevelRunEmphasis': array(31.84840384),
 'original_glrlm_LongRunEmphasis': array(3.29529965),
 'original_glrlm_LongRunHighGrayLevelEmphasis': array(105.54818451),
 'original_glrlm_LongRunLowGrayLevelEmphasis': array(0.13195635),
 'original_glrlm_LowGrayLevelRunEmphasis': array(0.04753603),
 'original_glrlm_RunEntropy': array(3.61198096),
 'original_glrlm_RunLengthNonUniformity': array(774.68294466),
 'original_glrlm_RunLengthNonUniformityNormalized': array(0.5620964),
 'original_glrlm_RunPercentage': array(0.71008473),
 'original_glrlm_RunVariance': array(0.95156434),
 'original_glrlm_ShortRunEmphasis': array(0.7642796),
 'original_glrlm_ShortRunHighGrayLevelEmphasis': array(24.24330307),
 'original_glrlm_ShortRunLowGrayLevelEmphasis': array(0.03873046),
 'original_glszm_GrayLevelNonUniformity': array(15.43902439),
 'original_glszm_GrayLevelNonUniformityNormalized': array(0.18828079),
 'original_glszm_GrayLevelVariance': array(4.64083879),
 'original_glszm_HighGrayLevelZoneEmphasis': array(26.91463415),
 'original_glszm_LargeAreaEmphasis': array(9957.51219512),
 'original_glszm_LargeAreaHighGrayLevelEmphasis': array(299816.14634146),
 'original_glszm_LargeAreaLowGrayLevelEmphasis': array(349.71745065),
 'original_glszm_LowGrayLevelZoneEmphasis': array(0.10705579),
 'original_glszm_SizeZoneNonUniformity': array(21.92682927),
 'original_glszm_SizeZoneNonUniformityNormalized': array(0.26740036),
 'original_glszm_SmallAreaEmphasis': array(0.52875801),
 'original_glszm_SmallAreaHighGrayLevelEmphasis': array(15.03666609),
 'original_glszm_SmallAreaLowGrayLevelEmphasis': array(0.06123972),
 'original_glszm_ZoneEntropy': array(4.82660455),
 'original_glszm_ZonePercentage': array(0.04427646),
 'original_glszm_ZoneVariance': array(9447.41344438),
 'original_ngtdm_Busyness': array(3.30699699),
 'original_ngtdm_Coarseness': array(0.00442833),
 'original_ngtdm_Complexity': array(26.15890833),
 'original_ngtdm_Contrast': array(0.02307657),
 'original_ngtdm_Strength': array(0.16982068),
 'case_id': '1a7jTnjpn9.hdf5'}

In [ ]:
import h5py
with h5py.File("hdf5/1a7jTnjpn9.hdf5", "r") as hdf:
    print(f"HDF5 file datasets: {list(hdf.keys())}")
    print(f"HDF5 file attributes: {list(hdf.attrs.keys())}")
    noncon = hdf["noncon"][:]
    print(f"Shape of noncon volume: {noncon.shape}")

In [14]:
len([i for i in row.keys() if i in row_h.keys()])

131

In [15]:
len(row)

131

In [16]:
len(row_h)

131

In [17]:
row.keys()

dict_keys(['diagnostics_Versions_PyRadiomics', 'diagnostics_Versions_Numpy', 'diagnostics_Versions_SimpleITK', 'diagnostics_Versions_PyWavelet', 'diagnostics_Versions_Python', 'diagnostics_Configuration_Settings', 'diagnostics_Configuration_EnabledImageTypes', 'diagnostics_Image-original_Hash', 'diagnostics_Image-original_Dimensionality', 'diagnostics_Image-original_Spacing', 'diagnostics_Image-original_Size', 'diagnostics_Image-original_Mean', 'diagnostics_Image-original_Minimum', 'diagnostics_Image-original_Maximum', 'diagnostics_Mask-original_Hash', 'diagnostics_Mask-original_Spacing', 'diagnostics_Mask-original_Size', 'diagnostics_Mask-original_BoundingBox', 'diagnostics_Mask-original_VoxelNum', 'diagnostics_Mask-original_VolumeNum', 'diagnostics_Mask-original_CenterOfMassIndex', 'diagnostics_Mask-original_CenterOfMass', 'original_shape_Elongation', 'original_shape_Flatness', 'original_shape_LeastAxisLength', 'original_shape_MajorAxisLength', 'original_shape_Maximum2DDiameterColumn', 'original_shape_Maximum2DDiameterRow', 'original_shape_Maximum2DDiameterSlice', 'original_shape_Maximum3DDiameter', 'original_shape_MeshVolume', 'original_shape_MinorAxisLength', 'original_shape_Sphericity', 'original_shape_SurfaceArea', 'original_shape_SurfaceVolumeRatio', 'original_shape_VoxelVolume', 'original_firstorder_10Percentile', 'original_firstorder_90Percentile', 'original_firstorder_Energy', 'original_firstorder_Entropy', 'original_firstorder_InterquartileRange', 'original_firstorder_Kurtosis', 'original_firstorder_Maximum', 'original_firstorder_MeanAbsoluteDeviation', 'original_firstorder_Mean', 'original_firstorder_Median', 'original_firstorder_Minimum', 'original_firstorder_Range', 'original_firstorder_RobustMeanAbsoluteDeviation', 'original_firstorder_RootMeanSquared', 'original_firstorder_Skewness', 'original_firstorder_TotalEnergy', 'original_firstorder_Uniformity', 'original_firstorder_Variance', 'original_glcm_Autocorrelation', 'original_glcm_ClusterProminence', 'original_glcm_ClusterShade', 'original_glcm_ClusterTendency', 'original_glcm_Contrast', 'original_glcm_Correlation', 'original_glcm_DifferenceAverage', 'original_glcm_DifferenceEntropy', 'original_glcm_DifferenceVariance', 'original_glcm_Id', 'original_glcm_Idm', 'original_glcm_Idmn', 'original_glcm_Idn', 'original_glcm_Imc1', 'original_glcm_Imc2', 'original_glcm_InverseVariance', 'original_glcm_JointAverage', 'original_glcm_JointEnergy', 'original_glcm_JointEntropy', 'original_glcm_MCC', 'original_glcm_MaximumProbability', 'original_glcm_SumAverage', 'original_glcm_SumEntropy', 'original_glcm_SumSquares', 'original_gldm_DependenceEntropy', 'original_gldm_DependenceNonUniformity', 'original_gldm_DependenceNonUniformityNormalized', 'original_gldm_DependenceVariance', 'original_gldm_GrayLevelNonUniformity', 'original_gldm_GrayLevelVariance', 'original_gldm_HighGrayLevelEmphasis', 'original_gldm_LargeDependenceEmphasis', 'original_gldm_LargeDependenceHighGrayLevelEmphasis', 'original_gldm_LargeDependenceLowGrayLevelEmphasis', 'original_gldm_LowGrayLevelEmphasis', 'original_gldm_SmallDependenceEmphasis', 'original_gldm_SmallDependenceHighGrayLevelEmphasis', 'original_gldm_SmallDependenceLowGrayLevelEmphasis', 'original_glrlm_GrayLevelNonUniformity', 'original_glrlm_GrayLevelNonUniformityNormalized', 'original_glrlm_GrayLevelVariance', 'original_glrlm_HighGrayLevelRunEmphasis', 'original_glrlm_LongRunEmphasis', 'original_glrlm_LongRunHighGrayLevelEmphasis', 'original_glrlm_LongRunLowGrayLevelEmphasis', 'original_glrlm_LowGrayLevelRunEmphasis', 'original_glrlm_RunEntropy', 'original_glrlm_RunLengthNonUniformity', 'original_glrlm_RunLengthNonUniformityNormalized', 'original_glrlm_RunPercentage', 'original_glrlm_RunVariance', 'original_glrlm_ShortRunEmphasis', 'original_glrlm_ShortRunHighGrayLevelEmphasis', 'original_glrlm_ShortRunLowGrayLevelEmphasis', 'original_glszm_GrayLevelNonUniformity', 'original_glszm_GrayLevelNonUniformityNormalized', 'original_glszm_GrayLevelVariance', 'original_glszm_HighGrayLevelZoneEmphasis', 'original_glszm_LargeAreaEmphasis', 'original_glszm_LargeAreaHighGrayLevelEmphasis', 'original_glszm_LargeAreaLowGrayLevelEmphasis', 'original_glszm_LowGrayLevelZoneEmphasis', 'original_glszm_SizeZoneNonUniformity', 'original_glszm_SizeZoneNonUniformityNormalized', 'original_glszm_SmallAreaEmphasis', 'original_glszm_SmallAreaHighGrayLevelEmphasis', 'original_glszm_SmallAreaLowGrayLevelEmphasis', 'original_glszm_ZoneEntropy', 'original_glszm_ZonePercentage', 'original_glszm_ZoneVariance', 'original_ngtdm_Busyness', 'original_ngtdm_Coarseness', 'original_ngtdm_Complexity', 'original_ngtdm_Contrast', 'original_ngtdm_Strength', 'case_id', 'dataset'])

In [18]:
df_nii["original_firstorder_Mean"]

0    122.15636706640156
Name: original_firstorder_Mean, dtype: object

In [19]:
df_h["original_firstorder_Mean"]

0    125.17354009205528
Name: original_firstorder_Mean, dtype: object

In [20]:
df_nii["original_firstorder_Mean"]

0    122.15636706640156
Name: original_firstorder_Mean, dtype: object

. Diagnostic Columns (Metadata)

Columns beginning with:

diagnostics_Versions_*
diagnostics_Configuration_*
diagnostics_Image-original_*
diagnostics_Mask-original_*

Definition
These columns store information about the radiomics extraction process and the image properties. They are not radiomics features used for modeling.

Examples and meaning

diagnostics_Versions_PyRadiomics
Version of the PyRadiomics library used for feature extraction.

diagnostics_Versions_Numpy / SimpleITK / PyWavelet / Python
Versions of supporting libraries used in the pipeline.

diagnostics_Configuration_Settings
The parameters used during feature extraction.

diagnostics_Configuration_EnabledImageTypes
Which image transformations (original, wavelet, LoG) were enabled.

diagnostics_Image-original_Spacing
Voxel spacing of the CT image (millimeters).

diagnostics_Image-original_Size
Dimensions of the CT image.

diagnostics_Image-original_Mean / Minimum / Maximum
Basic statistics of CT intensity values.

diagnostics_Mask-original_VoxelNum
Number of voxels in the segmented tumor.

diagnostics_Mask-original_BoundingBox
Spatial limits of the tumor region.

diagnostics_Mask-original_CenterOfMass
Geometric center of the tumor mask.

***
Contribution to dataset
These columns are mainly used for:

• reproducibility of experiments
• quality control
• verifying CT image properties

They are usually removed before machine learning modeling.
***
2. Shape Features

Columns beginning with:

original_shape_*

Definition
These features describe the three-dimensional geometry of the tumor segmentation.

Examples

original_shape_Elongation
Measures how stretched the tumor shape is.

original_shape_Flatness
Indicates whether the tumor is flat or spherical.

original_shape_MajorAxisLength
Length of the main axis of the tumor.

original_shape_MinorAxisLength
Second principal axis of the tumor.

original_shape_Maximum3DDiameter
Largest distance between two tumor points.

original_shape_SurfaceArea
Surface area of the tumor.

original_shape_VoxelVolume
Tumor volume measured in voxels.

original_shape_Sphericity
How closely the tumor shape resembles a sphere.

Contribution to dataset
Shape features represent tumor morphology such as size, compactness, and irregularity.

These features can help differentiate tumor types because malignant tumors often have more irregular shapes.

3. First-Order Statistics (Intensity Features)

Columns beginning with:

original_firstorder_*

Definition
These features describe the statistical distribution of CT intensity values (Hounsfield Units) inside the tumor.

Examples

original_firstorder_Mean
Average CT intensity of the tumor.

original_firstorder_Median
Median HU value.

original_firstorder_Minimum
Lowest HU value inside the tumor.

original_firstorder_Maximum
Highest HU value inside the tumor.

original_firstorder_Variance
Variance of intensity values.

original_firstorder_Skewness
Asymmetry of the HU distribution.

original_firstorder_Kurtosis
Sharpness of the HU distribution peak.

original_firstorder_Entropy
Randomness of intensity values.

Contribution to dataset
These features represent tumor density and tissue composition.

They are useful for detecting fat, necrosis, or contrast enhancement patterns.

4. GLCM Features (Gray Level Co-occurrence Matrix)

Columns beginning with:

original_glcm_*

Definition
GLCM features describe how often pairs of intensity values occur next to each other in the image.

Examples

original_glcm_Contrast
Measures local intensity differences.

original_glcm_Correlation
Measures correlation between neighboring voxels.

original_glcm_Entropy
Measures randomness of texture.

original_glcm_Idm (Inverse Difference Moment)
Measures image smoothness.

Contribution to dataset
GLCM features capture tumor texture patterns and heterogeneity.

5. GLDM Features (Gray Level Dependence Matrix)

Columns beginning with:

original_gldm_*

Definition
These features measure how many neighboring voxels depend on a central voxel with similar intensity.

Examples

original_gldm_DependenceEntropy
Complexity of voxel dependence patterns.

original_gldm_DependenceVariance
Variation in dependence size.

original_gldm_LargeDependenceEmphasis
Presence of large homogeneous structures.

Contribution to dataset
These features describe local homogeneity and spatial dependence of intensities.

6. GLRLM Features (Gray Level Run Length Matrix)

Columns beginning with:

original_glrlm_*

Definition
These features analyze consecutive sequences (runs) of voxels that have the same intensity value.

Examples

original_glrlm_ShortRunEmphasis
Presence of short intensity runs.

original_glrlm_LongRunEmphasis
Presence of long homogeneous runs.

original_glrlm_RunEntropy
Randomness of run lengths.

Contribution to dataset
GLRLM features capture directional texture patterns and structural continuity.

7. GLSZM Features (Gray Level Size Zone Matrix)

Columns beginning with:

original_glszm_*

Definition
These features measure connected regions (zones) that share the same gray-level intensity.

Examples

original_glszm_SmallAreaEmphasis
Presence of small homogeneous zones.

original_glszm_LargeAreaEmphasis
Presence of large homogeneous zones.

original_glszm_ZoneEntropy
Randomness of zone distribution.

Contribution to dataset
GLSZM features describe spatial clustering of intensities within tumors.

8. NGTDM Features (Neighborhood Gray Tone Difference Matrix)

Columns beginning with:

original_ngtdm_*

Definition
These features compare a voxel intensity with the average intensity of its neighboring voxels.

Examples

original_ngtdm_Coarseness
Measures texture smoothness.

original_ngtdm_Busyness
Measures rapid intensity changes.

original_ngtdm_Contrast
Measures local contrast differences.

Contribution to dataset
These features represent texture granularity and local intensity variation.

9. Dataset Identification Columns

case_id
Unique identifier for each patient or scan.

dataset
Indicates which dataset the sample belongs to (for example HDF5 or NIfTI dataset).

Contribution to dataset
These columns allow tracking of cases and detecting potential dataset bias.

Overall Concept

Your radiomics dataset contains five main types of information:

Metadata (diagnostics columns)
Tumor shape features
Intensity statistics
Texture features
Dataset identifiers

Machine learning models usually use:

shape + intensity + texture features

while diagnostic metadata is removed.

In [7]:
ls = []
hdf5_folder = "/media/euphrates/DS-Backup/angiomyolipoma/ucsf-rmac-dataset"
rd_mics_hdf5 = "/media/euphrates/DS-Backup/csv_aml_ucsf_rmac"
for file in os.listdir(hdf5_folder):

    input_path = os.path.join(hdf5_folder, file)
    
    with h5py.File(input_path, "r") as f:

        image_array = f["portven"][:]
        mask_array = f["mask"][:]

        image = sitk.GetImageFromArray(image_array)
        mask = sitk.GetImageFromArray(mask_array)

        features = extractor.execute(image, mask)

        row_h= dict(features)
        row_h["case_id"] = file
        ls.append(row_h.values())
        
columns = ls[0]
rows = ls[1:]
df_np = pd.DataFrame(rows,columns = columns)
df_np.to_csv("/media/euphrates/DS-Backup/csv_aml_ucsf_rmac/hdf5.csv")

GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated

KeyError: "Unable to open object (object 'portven' doesn't exist)"