In [127]:
import pandas as pd
import numpy as np
import os

In [128]:
dk = pd.read_json("kits23.json")

In [129]:
dk

,case_id,gender,vital_status,vital_days_after_surgery,bmi,comorbidities,age_at_nephrectomy,hospitalization,er_visit,readmission,...,tumor_histologic_subtype,tumor_necrosis,tumor_isup_grade,positive_resection_margins,sarcomatoid_features,rhabdoid_features,last_preop_egfr,first_postop_egfr,last_postop_egfr,aua_risk_score
0,case_00000,male,censored,1958,29.47,"{'myocardial_infarction': False, 'congestive_h...",49,2,0.0,0.0,...,clear_cell_rcc,0.0,3,0.0,0.0,0.0,"{'days_before_nephrectomy': 54, 'value': 77.0}","{'days_after_nephrectomy': 184, 'value': 76.0}","{'days_after_nephrectomy': 1958, 'value': 83.0}",intermediate_risk
1,case_00001,male,censored,1669,33.71,"{'myocardial_infarction': False, 'congestive_h...",50,6,1.0,0.0,...,papillary_rcc,0.0,2,0.0,0.0,0.0,"{'days_before_nephrectomy': 1, 'value': 67.0}","{'days_after_nephrectomy': 117, 'value': 58.0}","{'days_after_nephrectomy': 1623, 'value': 58.0}",low_risk
2,case_00002,male,censored,1694,28.13,"{'myocardial_infarction': False, 'congestive_h...",74,1,0.0,0.0,...,papillary_rcc,0.0,2,0.0,0.0,0.0,"{'days_before_nephrectomy': None, 'value': None}","{'days_after_nephrectomy': 76, 'value': 85.0}","{'days_after_nephrectomy': 1694, 'value': 84.0}",high_risk
3,case_00003,female,censored,114,38.69,"{'myocardial_infarction': False, 'congestive_h...",43,0,0.0,0.0,...,chromophobe_rcc,0.0,na,0.0,0.0,0.0,"{'days_before_nephrectomy': 61, 'value': 86.0}","{'days_after_nephrectomy': 114, 'value': 80.0}","{'days_after_nephrectomy': 114, 'value': 80.0}",low_risk
4,case_00004,male,censored,500,28.59,"{'myocardial_infarction': False, 'congestive_h...",72,2,0.0,0.0,...,clear_cell_rcc,0.0,2,0.0,0.0,0.0,"{'days_before_nephrectomy': None, 'value': None}","{'days_after_nephrectomy': 500, 'value': 54.0}","{'days_after_nephrectomy': 500, 'value': 54.0}",low_risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484,case_00584,female,censored,1974,30.79,"{'myocardial_infarction': False, 'congestive_h...",68,2,0.0,0.0,...,angiomyolipoma,0.0,na,1.0,0.0,0.0,"{'days_before_nephrectomy': 74, 'value': 55.0}","{'days_after_nephrectomy': 1, 'value': 83.0}","{'days_after_nephrectomy': 1969, 'value': 69.0}",benign
485,case_00585,male,censored,938,24.16,"{'myocardial_infarction': False, 'congestive_h...",28,1,1.0,0.0,...,chromophobe_rcc,0.0,na,0.0,0.0,0.0,"{'days_before_nephrectomy': 14, 'value': None}","{'days_after_nephrectomy': 938, 'value': None}","{'days_after_nephrectomy': 938, 'value': None}",low_risk
486,case_00586,male,dead,1717,26.72,"{'myocardial_infarction': False, 'congestive_h...",65,2,0.0,0.0,...,papillary_rcc,0.0,2,0.0,0.0,0.0,"{'days_before_nephrectomy': 1, 'value': 67.0}","{'days_after_nephrectomy': 1, 'value': 53.0}","{'days_after_nephrectomy': 1552, 'value': 59.0}",low_risk
487,case_00587,male,censored,2084,29.10,"{'myocardial_infarction': False, 'congestive_h...",72,2,0.0,0.0,...,clear_cell_papillary,0.0,2,0.0,0.0,0.0,"{'days_before_nephrectomy': 920, 'value': None}","{'days_after_nephrectomy': 104, 'value': 83.0}","{'days_after_nephrectomy': 1280, 'value': 85.0}",low_risk
488,case_00588,female,censored,2206,31.59,"{'myocardial_infarction': False, 'congestive_h...",67,2,0.0,0.0,...,clear_cell_rcc,0.0,2,0.0,0.0,0.0,"{'days_before_nephrectomy': 63, 'value': 56.0}","{'days_after_nephrectomy': 86, 'value': 50.0}","{'days_after_nephrectomy': 1207, 'value': 30.0}",low_risk

### KITS23 non-aml

In [130]:
dftest = pd.read_csv("CSV_kits23_Test/Test_kits23.csv")

In [131]:
dftest.shape

(94, 130)

In [132]:
dftest["subset"] = "Original"

In [133]:
dftest.shape

(94, 131)

In [134]:
#Add data source column

dftest["data_source"] = "kits23"

In [135]:
dftest.shape

(94, 132)

### KITS23 META

In [136]:
dk_meta = pd.read_json("kits23.json")

In [137]:
dk_meta

,case_id,gender,vital_status,vital_days_after_surgery,bmi,comorbidities,age_at_nephrectomy,hospitalization,er_visit,readmission,...,tumor_histologic_subtype,tumor_necrosis,tumor_isup_grade,positive_resection_margins,sarcomatoid_features,rhabdoid_features,last_preop_egfr,first_postop_egfr,last_postop_egfr,aua_risk_score
0,case_00000,male,censored,1958,29.47,"{'myocardial_infarction': False, 'congestive_h...",49,2,0.0,0.0,...,clear_cell_rcc,0.0,3,0.0,0.0,0.0,"{'days_before_nephrectomy': 54, 'value': 77.0}","{'days_after_nephrectomy': 184, 'value': 76.0}","{'days_after_nephrectomy': 1958, 'value': 83.0}",intermediate_risk
1,case_00001,male,censored,1669,33.71,"{'myocardial_infarction': False, 'congestive_h...",50,6,1.0,0.0,...,papillary_rcc,0.0,2,0.0,0.0,0.0,"{'days_before_nephrectomy': 1, 'value': 67.0}","{'days_after_nephrectomy': 117, 'value': 58.0}","{'days_after_nephrectomy': 1623, 'value': 58.0}",low_risk
2,case_00002,male,censored,1694,28.13,"{'myocardial_infarction': False, 'congestive_h...",74,1,0.0,0.0,...,papillary_rcc,0.0,2,0.0,0.0,0.0,"{'days_before_nephrectomy': None, 'value': None}","{'days_after_nephrectomy': 76, 'value': 85.0}","{'days_after_nephrectomy': 1694, 'value': 84.0}",high_risk
3,case_00003,female,censored,114,38.69,"{'myocardial_infarction': False, 'congestive_h...",43,0,0.0,0.0,...,chromophobe_rcc,0.0,na,0.0,0.0,0.0,"{'days_before_nephrectomy': 61, 'value': 86.0}","{'days_after_nephrectomy': 114, 'value': 80.0}","{'days_after_nephrectomy': 114, 'value': 80.0}",low_risk
4,case_00004,male,censored,500,28.59,"{'myocardial_infarction': False, 'congestive_h...",72,2,0.0,0.0,...,clear_cell_rcc,0.0,2,0.0,0.0,0.0,"{'days_before_nephrectomy': None, 'value': None}","{'days_after_nephrectomy': 500, 'value': 54.0}","{'days_after_nephrectomy': 500, 'value': 54.0}",low_risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484,case_00584,female,censored,1974,30.79,"{'myocardial_infarction': False, 'congestive_h...",68,2,0.0,0.0,...,angiomyolipoma,0.0,na,1.0,0.0,0.0,"{'days_before_nephrectomy': 74, 'value': 55.0}","{'days_after_nephrectomy': 1, 'value': 83.0}","{'days_after_nephrectomy': 1969, 'value': 69.0}",benign
485,case_00585,male,censored,938,24.16,"{'myocardial_infarction': False, 'congestive_h...",28,1,1.0,0.0,...,chromophobe_rcc,0.0,na,0.0,0.0,0.0,"{'days_before_nephrectomy': 14, 'value': None}","{'days_after_nephrectomy': 938, 'value': None}","{'days_after_nephrectomy': 938, 'value': None}",low_risk
486,case_00586,male,dead,1717,26.72,"{'myocardial_infarction': False, 'congestive_h...",65,2,0.0,0.0,...,papillary_rcc,0.0,2,0.0,0.0,0.0,"{'days_before_nephrectomy': 1, 'value': 67.0}","{'days_after_nephrectomy': 1, 'value': 53.0}","{'days_after_nephrectomy': 1552, 'value': 59.0}",low_risk
487,case_00587,male,censored,2084,29.10,"{'myocardial_infarction': False, 'congestive_h...",72,2,0.0,0.0,...,clear_cell_papillary,0.0,2,0.0,0.0,0.0,"{'days_before_nephrectomy': 920, 'value': None}","{'days_after_nephrectomy': 104, 'value': 83.0}","{'days_after_nephrectomy': 1280, 'value': 85.0}",low_risk
488,case_00588,female,censored,2206,31.59,"{'myocardial_infarction': False, 'congestive_h...",67,2,0.0,0.0,...,clear_cell_rcc,0.0,2,0.0,0.0,0.0,"{'days_before_nephrectomy': 63, 'value': 56.0}","{'days_after_nephrectomy': 86, 'value': 50.0}","{'days_after_nephrectomy': 1207, 'value': 30.0}",low_risk

### Add meta data into radiomics

In [138]:
#dfK = dfK.merge(dk_meta[["case_id","age_at_nephrectomy","gender","tumor_histologic_subtype","tumor_isup_grade","pathologic_size"]],on='case_id', how='inner')

In [139]:
dftest.shape

(94, 132)

In [140]:
# Define the mapping of KiTS23 columns to your Master Metadata names
rename_map = {
    "age_at_nephrectomy": "age",
    "gender": "gender",
    "tumor_histologic_subtype": "pathology_label",
    "tumor_isup_grade": "pathology_grade",
    "pathologic_size": "tumor_size"
}

# Perform the inner join and rename columns
dftest = dftest.merge(
    dk_meta[["case_id"] + list(rename_map.keys())], 
    on='case_id', 
    how='inner'
).rename(columns=rename_map)

# Quick check of the result
print(f"Joined KiTS dataframe shape: {dftest.shape}")
print(dftest[['case_id', 'pathology_label', 'tumor_size']].head())

Joined KiTS dataframe shape: (94, 137)
      case_id  pathology_label  tumor_size
0  case_00580   clear_cell_rcc         2.5
1  case_00588   clear_cell_rcc         2.9
2  case_00585  chromophobe_rcc         1.9
3  case_00586    papillary_rcc         2.2
4  case_00582   clear_cell_rcc         2.1

In [141]:
dftest.shape

(94, 137)

In [142]:
#Numeric columns
ls_numeric = dftest.loc[:,"original_shape_Elongation":"original_ngtdm_Strength"].columns.to_list()

In [143]:
len(ls_numeric)

107

In [144]:
ls_numeric.extend(["age","tumor_size"])

In [145]:
len(ls_numeric)

109

In [146]:
dftest['gender'].value_counts()

gender
male      66
female    28
Name: count, dtype: int64

In [147]:
dftest.gender = dftest.gender.map({"female":0,"F":0,"male":1,"M":1})

In [148]:
dftest.gender.value_counts()

gender
1    66
0    28
Name: count, dtype: int64

In [149]:
X = dftest.loc[:,ls_numeric]

In [150]:
import pickle

In [151]:
with open("/home/euphrates/Desktop/dreps/DS/Radiomics/CSV/PICKLE/scaler.pkl","rb") as f :
    scaler = pickle.load(f)

In [152]:
with open("/home/euphrates/Desktop/dreps/DS/Radiomics/CSV/PICKLE/model.pkl","rb") as f :
    model = pickle.load(f)

In [153]:
X = scaler.transform(X)

In [154]:
predictions = model.predict(X)

In [155]:
df = dftest[["case_id","pathology_label"]]

In [156]:
df['prediction'] = predictions

/tmp/ipykernel_4342/3931593458.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['prediction'] = predictions

In [157]:
pd.set_option("display.max_rows",100)

In [158]:
df

       case_id              pathology_label  prediction
0   case_00580               clear_cell_rcc           0
1   case_00588               clear_cell_rcc           0
2   case_00585              chromophobe_rcc           0
3   case_00586                papillary_rcc           0
4   case_00582               clear_cell_rcc           0
5   case_00584               angiomyolipoma           0
6   case_00587         clear_cell_papillary           0
7   case_00583               clear_cell_rcc           0
8   case_00575               clear_cell_rcc           0
9   case_00581                   oncocytoma           0
10  case_00579               clear_cell_rcc           0
11  case_00577                        other           0
12  case_00576                papillary_rcc           0
13  case_00578                   oncocytoma           0
14  case_00574               clear_cell_rcc           0
15  case_00573               clear_cell_rcc           0
16  case_00571               clear_cell_rcc           0
17  case_00572                        other           0
18  case_00568                   oncocytoma           0
19  case_00570               angiomyolipoma           0
20  case_00566               clear_cell_rcc           0
21  case_00569               angiomyolipoma           0
22  case_00567               clear_cell_rcc           0
23  case_00565                   oncocytoma           0
24  case_00561               clear_cell_rcc           0
25  case_00559               clear_cell_rcc           0
26  case_00562               clear_cell_rcc           0
27  case_00564               clear_cell_rcc           0
28  case_00560                  wilms_tumor           1
29  case_00563                papillary_rcc           0
30  case_00558              chromophobe_rcc           0
31  case_00557               clear_cell_rcc           0
32  case_00554                        other           0
33  case_00555         clear_cell_papillary           0
34  case_00556              chromophobe_rcc           1
35  case_00545               clear_cell_rcc           0
36  case_00551               clear_cell_rcc           0
37  case_00552               clear_cell_rcc           0
38  case_00553                        other           0
39  case_00548               clear_cell_rcc           0
40  case_00550                         None           0
41  case_00542               clear_cell_rcc           0
42  case_00546               clear_cell_rcc           0
43  case_00544                         None           0
44  case_00547  transitional_cell_carcinoma           0
45  case_00543               clear_cell_rcc           0
46  case_00549               clear_cell_rcc           0
47  case_00541                         None           0
48  case_00531              chromophobe_rcc           0
49  case_00540                papillary_rcc           0
50  case_00532  transitional_cell_carcinoma           0
51  case_00538               clear_cell_rcc           0
52  case_00537               clear_cell_rcc           0
53  case_00539               clear_cell_rcc           0
54  case_00535                papillary_rcc           0
55  case_00533               clear_cell_rcc           0
56  case_00524  transitional_cell_carcinoma           0
57  case_00530               clear_cell_rcc           0
58  case_00536               clear_cell_rcc           0
59  case_00534                   oncocytoma           0
60  case_00523               clear_cell_rcc           0
61  case_00522               clear_cell_rcc           0
62  case_00521                         cyst           1
63  case_00520  transitional_cell_carcinoma           0
64  case_00519                   oncocytoma           0
65  case_00518         clear_cell_papillary           0
66  case_00514                         None           0
67  case_00517  transitional_cell_carcinoma           0
68  case_00513                papillary_rcc           0
69  case_00516                  wilms_tumor           1
70  case_00512                         None           0
71  case_00511              chromophobe_rcc           0
72  case_00515                        other           0
73  case_00506                   oncocytoma           0
74  case_00509              chromophobe_rcc           0
75  case_00510               clear_cell_rcc           0
76  case_00508               clear_cell_rcc           0
77  case_00507               clear_cell_rcc           0
78  case_00505               clear_cell_rcc           0
79  case_00504               clear_cell_rcc           0
80  case_00502        spindle_cell_neoplasm           0
81  case_00499               clear_cell_rcc           0
82  case_00501                   oncocytoma           0
83  case_00503               clear_cell_rcc           0
84  case_00496               clear_cell_rcc           0
85  case_00500               clear_cell_rcc           0
86  case_00498               clear_cell_rcc           0
87  case_00497               clear_cell_rcc           0
88  case_00491               clear_cell_rcc           0
89  case_00495               clear_cell_rcc           0
90  case_00494               clear_cell_rcc           0
91  case_00493               clear_cell_rcc           0
92  case_00492  transitional_cell_carcinoma           0
93  case_00490  transitional_cell_carcinoma           0